# Generated by Django 3.1.1 on 2020-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
