# Generated by Django 3.1.1 on 2020-09-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abcapp', '0002_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcapp.marcas')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcapp.presentacion')),
            ],
        ),
    ]
